---
site_name: Cely
copyright: Copyright &copy; 2019 <a href="http://celylog.in">Cely</a>
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - swift
  # custom_dir: theme
extra_css:
  # - css/breadcrumbs.css
  # - css/fabric.css
  # - css/cely.css
  # - css/sidenav.css
  # - css/code.css
nav:
# - Home: index.md
# - Installation: 'includes/installing-cely.md'
- Usage:
  - Basic: usage/basic_usage.md
  - Advance: usage/advance_usage.md
- Guides:
  - Introduction: guides/introduction.md
  - Quiet Re-Authentication: guides/quiet_re-authentication_flow.md
  - Loud Re-Authentication: guides/loud_re-authentication_flow.md
  - Add FaceID/Touch: guides/add_biometric_authentication.md
- API:
  - Cely: api/index.md
  - Protocols: api/protocols.md
  - Constants: api/constants.md
- Understanding Keychain: understanding_keychain.md

markdown_extensions:
  - toc:
      permalink: "#"
  - markdown_include.include
